Rails Forms
kenderb/re-former pull request #1
Opened 2020-11-20 17:56 UTC by julian3493

- We create a user model with username, email, and password fields.
- We add validations for each field in the user model.
- We create a form template.
- We create index, new, show, edit, create, update, and destroy actions in the user controller.
- We create a view for new, index, edit, and show actions.

2020-11-20 18:48 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

#### Nice work team 👏  

You've done an awesome job so far 👌. But there are still some changes that are necessary for this project to be approved.

- [x] Your route in config/routes.rb should contain:  resources :users, only: [:new, :create, :edit, :update] ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_route1.png) [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_route2.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))

#### It is important to know how building forms evolved to form_for 
([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form1.png) [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form2.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms)) Let's add these missing piece of code to our `_form.html.erb` file and we will be done.

* A commented out form built without a rails helper using 
`users_path` helper for action ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form1.png) [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form2.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))

* A commented out form built with `form_tag` a rails helper ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form_tag2.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))

* Finally a form with `form_for` tag using `@user` from the controller ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form_for.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))

#### Kindly refer to the comment I made on your code base about views related logic

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-11-20 18:48 UTC, acushlakoncept commented on app/views/users/_form.html.erb
> +  <% end %>
View-related logic can be encapsulated in View helpers (app/helpers/*_helper.rb)
* [ ] There should be absolutely NO logic in views. >Views are only for displaying information that became available to it from its corresponding controller not generating it. **Resources**
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
*[Rails View Helpers Best Practices  @Guide](https://medium.com/@acushla4real/rails-view-helpers-best-practices-guide-d7d7b6db3db4)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

2020-11-20 22:58 UTC, blackpintz requested changes
# Status: Changes Required

### Hello team 😃,

**Good job implementing the requested changes 💪. However, there are still a few fixes needed.**

1). **I get the following error when I visit `new_user_path` and `edit_user_path`.**
![pdfError](https://user-images.githubusercontent.com/38922385/99856449-0b54d900-2b9a-11eb-97e8-35ad60f7bd1d.png)

2). **Add the following in your Readme getting started manual.**

- Add the command for running migrations.

- Show the routes one needs to visit in order to create and edit a user.

- [optional] You can explain or provide documentation that is useful for installing `yarn` and postrgres.

3) **Check more in the comments below.**

### Happy coding 😃.

**PS: You can reach me on slack (Rose Wanjohi).**

2020-11-20 22:58 UTC, blackpintz commented on app/controllers/users_controller.rb
> +        format.json { render :show, status: :created, location: @user }
It should `redirect_to new_user_path` if a new user is successfully saved.

2020-11-20 22:58 UTC, blackpintz commented on app/controllers/users_controller.rb
> +        format.json { render :show, status: :created, location: @user }
It should `redirect_to edit_user_path` if the user was updated successfully.

2020-11-20 22:58 UTC, blackpintz commented on app/views/users/_form.html.erb
> +=end%>
This code should be commented out.

2020-11-20 22:58 UTC, blackpintz commented on app/views/users/_form.html.erb
> +=end%>
This code should be commented out.

2020-11-21 01:23 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @julian3493 and @kenderb, great job fixing most of the comments outlined bt the previous TSE's :smile: The form is working as expected, there is one thing I would like us to fix before proceeding: :+1:  Kindly check the comment below
- Let us use only the working controller methods, for example in our `users controller` we have defined the `show` and `edit` method but it is empty and not working so it is not advisable to declare it as a resource in our routes

Kindly submit another code review once this is fixed :smile: 
_Happy coding_ :man_technologist:
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-11-21 02:14 UTC, addod19 approved these changes
## Status: Approved :trophy: :balloon: 

Hi @julian3493 and @kenderb, congratulations on a great job done :fireworks: I hereby approve the project :slightly_smiling_face: 

Go ahead and merge into development :+1: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](linkedin.com/in/daniel-larbi-addo/)

2020-11-21 02:15 UTC, merged